name: LUCAUS CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build bootJar
        run: ./gradlew clean bootJar -x test

      - name: Create secret yml
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.APPLICATION_SECRET_YML }}" > application-secret.yml

      - name: Grant execute permission for scripts
        if: github.ref == 'refs/heads/main'
        run: chmod +x scripts/stop.sh scripts/start.sh

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip deploy files
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p deploy
          cp build/libs/*SNAPSHOT.jar deploy/application.jar
          cp appspec.yml deploy/
          cp -r scripts/ deploy/
          cp application-secret.yml deploy/
          cd deploy && zip -r ../deploy.zip .

      - name: Upload to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 cp deploy.zip s3://lucaus-codedeploy-artifacts-994851303288-ap-northeast-2-an/deploy/deploy.zip

      - name: Deploy to CodeDeploy
        if: github.ref == 'refs/heads/main'
        run: |
          aws deploy create-deployment \
            --application-name lucaus-codedeploy \
            --deployment-group-name lucaus-codedeploy-group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=lucaus-codedeploy-artifacts-994851303288-ap-northeast-2-an,key=deploy/deploy.zip,bundleType=zip