name: LUCAUS CICD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          cat > src/main/resources/application.yml <<'EOF'
          ${{ secrets.APPLICATION_YML }}
          EOF

      - name: Create application-local.yml
        run: |
          mkdir -p src/main/resources
          cat > src/main/resources/application-local.yml <<'EOF'
          ${{ secrets.APPLICATION_LOCAL_YML }}
          EOF

      - name: Create application-secret.yml
        run: |
          mkdir -p src/main/resources
          cat > src/main/resources/application-secret.yml <<'EOF'
          ${{ secrets.APPLICATION_SECRET_YML }}
          EOF

      - name: DEBUG yml 확인
        run: |
          echo "===== application.yml ====="
          cat src/main/resources/application.yml
          echo "===== application-local.yml ====="
          cat src/main/resources/application-local.yml
          echo "===== application-secret.yml ====="
          cat src/main/resources/application-secret.yml

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace -Dspring.profiles.active=local